version: '3'

services:
  graalvm-project:
    image: graalvm-project:latest
    container_name: graalvm-project-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
